### PR TITLE
add materialized views

### PR DESCRIPTION
**Pull request by maximepvrt**

### CODE REVIEW

**Comment by tpetry** [comment]
Thanks for your PR, give me some time to review it. I am playing with the idea for a long time to add view options like this:

```php
Schema::createView('myview', ....)
  ->recursive()
  ->materialized();
```

If this is not possible, I will merge your code ;)

**Comment by maximepvrt** [comment]
@tpetry I added dropping materialized views

**Comment by tpetry** [comment]
I've changed your implementation a little by:

1. Added support for `WITH [NO] DATA` as this enables very fast migrations by delaying the work to fill the view.
2. Removed the `dropMaterializedViewIfExists` function as this is not a native PostgreSQL command and adding a single line to do the same is no problem for the user.
3. Added a complete chapter in the readme  for a more descriptive explanation

I would tweet tomorrow of that new feature, do you have a Twitter account so I can give you credit for that feature?

**Comment by maximepvrt** [comment]
Perfect !
Yes my Twitter handle is @maximepvrt too

**Pull request merged**
