### PR TITLE
Allow defining columns of the view

### PR DESCRIPTION
**Pull request by bastien-phi**
When creating a view, it could be useful to define the columns before the query.

```sql
create or replace view "test_623632" ("column_449989") as select random()
```

Real-life use case of this : I want a view to be created as a union query of different tables. Some columns have to be renamed, other defined with static values, ... It would be possible to do it without defining the columns before the query but the syntax of the query would become very heavy.

This syntax is borrowed from `staudenmeir/laravel-migration-views` (https://github.com/staudenmeir/laravel-migration-views) but the two packages are not compatible.

### CODE REVIEW

**Comment by tpetry** [comment]
The materialized view would need the columns param too to be consistent with the other ones.

**Comment by bastien-phi** [comment]
Here it is !

**Comment by tpetry** [comment]
Thanks for your work Bastien, again. Its released as `0.32.0`

**Comment by bastien-phi** [comment]
Always fun to contribute ! Actually, I needed this for my current project :sweat_smile:

**Pull request merged**
