### PR TITLE
Allow functional CTE definition

### PR DESCRIPTION
**Pull request by glamax13**
Hello,

Thanks a lot for all the twitter tips, the great digital book and this package, they really helped me a lot!

I was wondering if you would allow to define recursive CTE that are functions.

I actually have a valid use case for this: i have to get distinct ids on millions of rows in a quick way and the best way to do it was with an example i found [here](https://explainextended.com/2009/05/03/postgresql-optimizing-distinct/).
Postgres doesn't have the best DISTINCT implementation so that is the best i could find.
A comment of this post explain how it can be done with a CTE:
```
WITH RECURSIVE t(n) AS (
  SELECT MIN(grouper) FROM t_distinct
  UNION ALL
  SELECT (
    SELECT t_distinct.grouper 
    FROM t_distinct
    WHERE t_distinct.grouper > n
    ORDER BY t_distinct.grouper
    LIMIT 1
  )
  FROM t WHERE n IS NOT NULL
)
SELECT n FROM t;
```

If you have an alternative, or improvements i would love to here it but that is not why i'm here today!

My issue is that the whole CTE name is wraped when it is declared but i would need to wrap the function name and the arguments separately.

It can be done in a more compact way but i wanted it to be as clear as possible.

Thank you for your time.

### CODE REVIEW

**Comment by tpetry** [comment]
Can you share an example query which is not possible to build with the current implementation?  The shared query looks fine to me and should be supported.

**Comment by glamax13** [comment]
Sure thing!

My Eloquent query looks like this:
```
		$aliasedColumn = "travel.{$column}";
		$cteQuery = Travel::query()
			->addSelectAgg($column, 'min', null, 'n')
			->union(
				DB::query()
					->from('t')
					->selectSub(
						static::getFilteredTravel()
							->select($aliasedColumn)
							->whereColumn($aliasedColumn, '>', 'n')
							->orderBy($aliasedColumn)
							->limit(1),
						'filter'
					)->whereNotNull('n'),
			);

		$query = DB::query()
			->from('t')
			->select('n')
			->withExpression('t(n)', $cteQuery, [
				'recursive' => true,
			]);

		dd($query->toSql());
```
This generates:
```
with recursive "t(n)" as (
	(
		select MIN("departure_location_id") AS "n"
		from "travel"
	)
	union
	(
		select (
				select "travel"."departure_location_id"
				from "travel"
				where "travel"."departure_location_id" > "n"
				order by "travel"."departure_location_id" asc
				limit 1
			) as "filter"
		from "t"
		where "n" is not null
	)
)
select "n"
from "t"
```
Which result in the error 'relation "t" does not exist'.

The expected result would instead be:
```
with recursive "t"("n") as (
	(
		select MIN("departure_location_id") AS "n"
		from "travel"
	)
	union
	(
		select (
				select "travel"."departure_location_id"
				from "travel"
				where "travel"."departure_location_id" > "n"
				order by "travel"."departure_location_id" asc
				limit 1
			) as "filter"
		from "t"
		where "n" is not null
	)
)
select "n"
from "t"
```

Not much of a difference but it makes the query fail.
I tried wrapping the table name in an Expression object as i saw those are supposed to be ignore during the wrapTable() execution but didn't seemed to work.

Hope this helps.

**Comment by tpetry** [comment]
This is incorrect. You are not providing a table name:
```php
->withExpression('t(n)', $cteQuery, [
```

This should work:
```php
->withExpression('t', $cteQuery, [
```

**Comment by glamax13** [comment]
I know i have tried removing parameters but i guess i misinterpreted an unrelated error message...

It does indeed work with 't(n)' and as 't', so those changes are necessary.
My apologize.

Thank you for your answers and i wish you a good continuation.

**Pull request closed without merging**
